### ISSUE TITLE
why do you use prediction_model to evaluate? why not use the model used during training? 

### ISSUE THREAD

**Issue by dhiaul98** [xuannianz/EfficientDet#132]
why do you use prediction_model to evaluate? why not use the model used during training?

**Comment by DujeMedak** [comment]
Hi @dhiaul98 , I believe the prediction model is used because the evaluation function expects decoded outputs from the network. If you look at the efficientdet function in model.py you'll see the difference between the model used for training and prediction model is their output layer. Training model has classification and regression layers as its output, which makes it possible to directly calculate loss during the training process. The prediction model (that is used in evaluation) has the same weights as the training model but it has extra layers used for decoding (and filtering) the output of the network into final predictions which can then be used to evaluate the model performance. Hope this answer helps!

**Comment by dhiaul98** [comment]
Oke sir, i'am sorry about that, i'am newbie in this field :D
