### ISSUE TITLE
how to design anchor ratios and scales?

### ISSUE THREAD

**Issue by lucasjinreal** [xuannianz/EfficientDet#154]
wanna train on custom dataset, using default coco anchor settings, the big target can detect while small target always miss.

Did I miss something in such situation?

**Comment by DujeMedak** [comment]
Hi @jinfagang ,
You can find some information about designing anchors for custom dataset in issue #111. Hope it can help!

**Comment by lucasjinreal** [comment]
I still don't know how to apply such anchor, does there any snippets to do so?

**Comment by SiBensberg** [comment]
Create a new anchor Object in generators/common.py
for example:
```
myAnchors = AnchorParameters(
    sizes=[32, 64, 128, 256, 512],
    strides=[8, 16, 32, 64, 128],
    # ratio=h/w
    ratios=np.array([0.634, 1, 1.577], keras.backend.floatx()),
    scales=np.array([0.4, 0.506, 0.641], keras.backend.floatx()),
)
```
then edit line 45:
```
self.anchor_parameters = myAnchors
```

Do not change the sizes or strides. If you do not want to change more code else it will most probably break the model. If you want to detect smaller objects, simply try smaller scales.

**Comment by lucasjinreal** [comment]
Yes, I know this, what I means is how to get such values:
```
ratios=np.array([0.634, 1, 1.577],
    scales=np.array([0.4, 0.506, 0.641], 
```
on my own dataset. Is that generated by a snippet? Like yolo? But yolo not using this format anchor.

What's the meaning of scales? (ratios I know is the shape of the box), is that minimal box inside dataset according to image_w or image_h?

**Comment by DujeMedak** [comment]
Hi, @jinfagang , unfortunately this snippet does't generate new scales or aspect ratios it only helps you set some precalculated values. Calculation can be done using the repository I mention in the issue (anchor optimization for RetinaNet) but I am afraid there isn't a simple snippet that would allow you to calculate this value easier than that. 

Looking at the anchors.py it looks almost identical to the one from RetineNet repository so the meaning of scales is probably the same. I think it easier to find more information about this in that other repository since its older and has more resolved issues. For example, take a look at https://github.com/fizyr/keras-retinanet/issues/780#issuecomment-435807815 for a simple explanation of scales. 
 I hope this comment helped you!

**Comment by lucasjinreal** [comment]
So many thanks! From link of retinanet, i think it is scale of FPN size, do u know how's that of effixientdet? If i want my miminual box size to be 8pixel, and my image is 1920*1080, what could be the min scale?

**Comment by DujeMedak** [comment]
> i think it is scale of FPN size

Actually it is the size of an anchor for a particular FPN level. If you look at anchors.py and check the default parameters for anchors you'll notice there is a parameter called sizes. 
This parameter determines how big will be your anchor for a particular level of FPN. I think these sizes refer to anchors of aspect ratio 1 meaning if you see size 32 it means an anchor with size 32x32. As @SiBensberg  already stated, I don't think its a good idea to change these values. You can change the scale so that multiplied with this base size it gives you a wanted box. I got to this conclusion by looking at the generate_anchors function.  I created a small snippet that uses generate_anchors function for some particular ratios and scales. You can try to play around a bit with this and see how to get your wanted anchors size. (Spoiler alert! If you want to get an anchor of 8x8 and you already have defined base anchors size of 16x16 you should probably set one of the scales to 0.5). I hope what I wrote here is correct and it is actually how the anchors should be calculated and I hope the snippet can help you.

```
import numpy as np

def generate_anchors(base_size=16, ratios=None, scales=None):
    """
    Generate anchor (reference) windows by enumerating aspect ratios X scales w.r.t. a reference window.
    Args:
        base_size:
        ratios:
        scales:
    Returns:
    """
    if ratios is None:
        ratios = AnchorParameters.default.ratios

    if scales is None:
        scales = AnchorParameters.default.scales

    num_anchors = len(ratios) * len(scales)

    # initialize output anchors
    anchors = np.zeros((num_anchors, 4))

    anchors[:, 2:] = base_size * np.tile(np.repeat(scales, len(ratios))[None], (2, 1)).T

    areas = anchors[:, 2] * anchors[:, 3]

    # correct for ratios
    anchors[:, 2] = np.sqrt(areas / np.tile(ratios, len(scales)))
    anchors[:, 3] = anchors[:, 2] * np.tile(ratios, len(scales))

    anchors[:, 0::2] -= np.tile(anchors[:, 2] * 0.5, (2, 1)).T
    anchors[:, 1::2] -= np.tile(anchors[:, 3] * 0.5, (2, 1)).T

    return anchors

sizes=[32, 64, 128, 256, 512]
strides=[8, 16, 32, 64, 128],
# ratio=h/w
ratios=np.array([1, 0.5, 2], dtype=np.float32)
scales=np.array([2 ** 0, 2 ** (1.0 / 3.0), 2 ** (2.0 / 3.0)], dtype=np.float32)

anchors = generate_anchors(base_size=16, ratios=ratios, scales=scales)
n_scales = len(scales)
for ind, an in enumerate(anchors):
    if ind%n_scales == 0:
        print("anchors for scale", scales[int(ind/n_scales)], ":")
    print("\t", an)
```

**Comment by lucasjinreal** [comment]
I using your code generates negative anchor sizes:

```
Using TensorFlow backend.
anchors for scale 1.0 :
	 [-8. -8.  8.  8.]
	 [-11.3137085   -5.65685425  11.3137085    5.65685425]
	 [ -5.65685425 -11.3137085    5.65685425  11.3137085 ]
anchors for scale 1.2599211 :
	 [-10.07936859 -10.07936859  10.07936859  10.07936859]
	 [-14.25437976  -7.12718988  14.25437976   7.12718988]
	 [ -7.12718988 -14.25437976   7.12718988  14.25437976]
anchors for scale 1.587401 :
	 [-12.69920826 -12.69920826  12.69920826  12.69920826]
	 [-17.95939255  -8.97969628  17.95939255   8.97969628]
	 [ -8.97969628 -17.95939255   8.97969628  17.95939255]

```

So how can I draw these anchors on my original image? I wanna check if these anchor covers minimal sizes targets or not?

**Comment by DujeMedak** [comment]
It is normal to have negative coordinates because all of the boxes are centered around 0. These boxes are then further placed on your image in anchors_for_shape function. This function will take into account the stride (spacing in between two adjacent anchors) and your original image size. If you want to see the placement on your original image you'll have to combine some more functions from anchors.py script. Another way is to use debug.py script from RetinaNet repository. This script will display your images and annotations and it will display all the annotations that don't have any available anchors in red.
