### ISSUE TITLE
Retrain w/ own Dataset:

### ISSUE THREAD

**Issue by HaiLongEmb** [xuannianz/EfficientDet#22]
hi, @xuannianz :

I'm trying to train on my dataset， I have modify voc_classes.txt file（eg:person，dog、cat）。
Running train.py.
    str(weight_values[i].shape) + '.')
ValueError: Layer #495 (named "class_head"), weight <tf.Variable 'pyramid_classification/kernel:0' shape=(3, 3, 88, 27) dtype=float32> has shape (3, 3, 88, 27), but th
e saved weight has shape (180, 88, 3, 3).

Please help me out

Thx very much!

**Comment by HaiLongEmb** [comment]
I load  --snapshot pascal_05_0.6283_1.1975_0.8029.h5 start retrain, I don't know what to do now.

**Comment by xuannianz** [comment]
Hi @HaiLongEmb , you can use keras instead of tensorflow.keras, then set skip_mismatch=True option of model.load_weights().

**Comment by HaiLongEmb** [comment]
Great！

**Comment by bensuucar** [comment]
I would like to get a pretrained model and use it for another training with different class number. 
@xuannianz I followed your instructions here however I cannot use 'skip_mismatch = True ' because it throws an error every time:

Traceback (most recent call last):
  File "train.py", line 382, in <module>
    main()
  File "train.py", line 333, in main
    model.load_weights(args.snapshot, by_name=True, skip_mismatch=True )
TypeError: load_weights() got an unexpected keyword argument 'skip_mismatch'


I changed to keras instead of tensorflow.keras and I tried older versions of keras as well but it didnt work. 

Could you please help on this issue?

**Comment by SiBensberg** [comment]
@bensuucar
I could not make it work too. However my workaround is to modify the weights. I just cutted away the needless values with h5py. Now the training is running.
Below some sample Python code to shorten the 'pyramid_classification' Group.

```
with h5py.File('path/to/your/file.h5', 'r+') as weights_file:
    ## shorten kernel:0 values to 36
    #take a look at the shape
    print(weights_file['/model_weights/class_head/pyramid_classification/kernel:0'].shape)
    kernel = weights_file['model_weights']['class_head']['pyramid_classification']['kernel:0']
    kernelValues = kernel[()]
    shortenedKernelValues = np.delete(kernelValues, np.s_[36::1], 3)

    ## delete too long dataset and create new shorter one
    del weights_file['/model_weights/class_head/pyramid_classification/kernel:0']
    weights_file.create_dataset('/model_weights/class_head/pyramid_classification/kernel:0', data=shortenedKernelValues)

    #see if it worked:
    print(weights_file['model_weights']['class_head']['pyramid_classification']['kernel:0'].shape)

    ## shorten bias:0 values to 36
    # take a look at the shape:
    print(weights_file['model_weights/class_head/pyramid_classification/bias:0'][()].shape)
    biasValues = weights_file['model_weights/class_head/pyramid_classification/bias:0'][()]
    shortenedBias = np.delete(biasValues, np.s_[36::1])

    # delete too long bias and create new one with shorter array
    del weights_file['/model_weights/class_head/pyramid_classification/bias:0']
    weights_file.create_dataset('/model_weights/class_head/pyramid_classification/bias:0', data=shortenedBias)

    # see if it worked
    print(weights_file['model_weights/class_head/pyramid_classification/bias:0'][()].shape)
```

I needed to shorten it to 36 because my new dataset just has 4 classes. 4*9=36
You can also randomize the new datasets (shortenedKernelValues and shortenedBias) for a more "correct" way.

**Comment by lucyLLLL** [comment]
> I would like to get a pretrained model and use it for another training with different class number.
> @xuannianz I followed your instructions here however I cannot use 'skip_mismatch = True ' because it throws an error every time:
> 
> Traceback (most recent call last):
> File "train.py", line 382, in
> main()
> File "train.py", line 333, in main
> model.load_weights(args.snapshot, by_name=True, skip_mismatch=True )
> TypeError: load_weights() got an unexpected keyword argument 'skip_mismatch'
> 
> I changed to keras instead of tensorflow.keras and I tried older versions of keras as well but it didnt work.
> 
> Could you please help on this issue?

have you solve the issue?
